language: ruby

rvm:
- 2.1.2

branches:
  only:
  - master

before_script:
- travis_retry gem install bundler
- git config --global user.name "yasuoza(via Travis CI)"
- git config --global user.email "yasuharu.ozaki@gmail.com"
- git remote set-url origin $REPO.git
- if [ -z "$id_rsa_{1..23}" ]; then echo 'No $id_rsa_{1..23} found !' ; exit 1; fi
- echo -n $id_rsa_{1..23} >> ~/.ssh/travis_rsa_64
- base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- bundle exec rake setup_github_pages[$REPO]
- git checkout -- _config.yml

script:
- bundle exec rake gen_deploy

bundler_args: --without test development --deployment --jobs 8

cache: bundler

env:
  global:
  - REPO="git@github.com:yasuoza/blog.yasuoza.com"
  - secure: Hez8P5XoKICTFkPeNhdnRJGPGquhct5p69Lp3FUj2/8q0+MLXGS6fnxYu7fr3GG18qmYjJZwiXvEnmqmr7lcTaQekVwfOM2/dWqrnVGOmb5EZ7r3+UtkQferMtOu9L51sW/01Irbicbss71Fy95WIo9tL3ATqwP8mLF21g5AX40=
  - secure: ZEhCqr4ZCo4RvLGWqzfIQNGj2ZtwcKIYCCw13Pjthi4Kre0HeVZAc97DImLILgt7tpjAw4hPRs1/6vyg0hWkxTgfqCj+1lt/64CIm/wtY5UY8Xl1hO6vpUUTGPxE3s+yUA0sn+7p1CfpvHhUzIXmvKd07rLdF1k73ktu6e4m/Zs=
  - secure: UhCQHsW57iLkSLUdN9xf8uF/9IRIMIlIyai0jQ+FAIPLmsORFtwpBA9DmTN02odDrEX7oKlTXhMxuFFofemrGBX30wxvAYpcqmG/Xj9p9RyEkyo0SEtv+WTV/vjA/JoK3G313C+BldTpcY0yQjYHeB17pB2oXL31pLyj7Ur/z2o=
  - secure: I8iYpw0FGI7OCIF4c2LurYMEnsj5PKvkPgWSOs5Lo5pRvt5XJH9/MVXOC7/ZXoynMZtnv3BKIcgOR92KfRPle0+U2hjLWEfz46CfRMgyHVlVgm4abnKbLz9ceQHG5imyFl8olTX2q+sihHOwtCHOmLim2wT1/mYEIWXGOJRHQuw=
  - secure: HAN1cHSjlhI30eJ4KoF470jTzgoUYpZO1dmzt2dY1DyYbVFKPepECT3C5fuSgn1dlk8usM2iTYOb2HDHsST6WcCFaQcplVA9GeEu5ZPleSniQwmohwewuWXP55MVbHW8ETxQb2oIvs6qAdhM+PuDKxeIYCcXsCLHH34RNRgJXBc=
  - secure: NHCs47Hn4LeFpOpOuJFJjhNKqPRA7PVwbF8EJBgfEkCPXVBWFVFyp5X81njBUuYjcBF4Q/RE+1HJ7xKXRoOJBlM9q2NxK2IIsR8cBX2wstnpTCpQjB/Wf/tpJQrSxqL0/uQGLCxJvnWjLT2DtS3qL425sJ0F29Kw34AAhncSWgo=
  - secure: X8K9tsxMSmk5npQZ1cBNdc6TMbthpF30RKhwWWeKiE4+OR3Z0SJfxMuUGL2mc51DH4H0HHPqb8sndcqPbYP9Ex+7B0Y1L3wjMo4bhfQiiL4AqSylj1TAiIOnSyPlC5qy+JalHydc7i9hVhNC8eEYJqX9ipugUOvkhEchybiBEYk=
  - secure: fgTGkVHb7XiFQwK3cbOy0cgV48sO2iOte5u3c1tD0W1mx8cWkvAZNCGrlSwMxFr5uLUfEep4oqIXvxOJ/gKNbnXBIpMLmQVeRGVPETuksXx+QXhXkoK2sfWIHIeBShtgVXQHQbtLCuHCDBoR1HUah52+jdA3x62k6k3H1cD9QpI=
  - secure: fiuiR01chyiayFJFzBAyPi8mLodMj3J/F6uEg+rEP17H1pKgkITWNedJgBL6626zoNK3PFLL96SdR7mBgTTWUORBI98OBDKEW2PpWut2TaUZm6XLtOW0P7bpq4/UuoBgKsiZhYFg1LYUAK2d64/W7eD2zHh0WDAXWmMM4z30TEo=
  - secure: UoVRLdjbQDtYovtaO2ug4+/wgCrkmefgKU4hyCAvbETXKZu60fuGaR6yEKRYTHViYvEo1m8zcQQyhw2casSrNVE1xnT25qLaqeBBxzTtvenSWivNMPnAI1aDvGB06DAd8TXR8yNvZRfHBB7Kkvg/FyZdssAce0m20JG/TOfIKuU=
  - secure: JqwixA5KKOvhcqDyoLSiezStoegeFWYdFXe6dr6Zq/3E/vLFJXFAqfT9k3RSBCw9DbmT0pkY1zv1nR98UfEit6n91QOLbNHls7Zvz2hSf/EL0ONBwSxO/gtSiuPPyzOlvrU4DONVDiJpkZJEaV4fyJMhB7nJc0WQQSVIUd3ea1Y=
  - secure: XKOQOcAgKSw25E1Gr9pC3V5c60bXUxS/p67+PFeGzgyha1+6L/ihkl1KzkKL4d0FiqZJ8KK49hsiLNObj8VmEoCBjqF7aqODBgb3Rc4ZGX/hdAHjUUj7ECertGzRdx1WwiS3dRPUFJUtTglmthabp2rPM0pfFqMg9+5kBSN8Qiw=
  - secure: VL/WpAPwKCU1byHRasvQQx76cL/BBGD8ATlo8at+VvYmQRMcuamqFcno7YDhX0Yi/Q7is1T5P5DPehy284ysEoagVvAvUPG8LO/WzNGur+0ek/ycZhyWEyEskwx+9XD/fTtwNA6gJqZ/zZtyccfXVWTK/8iH8n7jISR9g/DlUG8=
  - secure: GdgbtxL3nV0XEk0sXedo2Y3xmR1Hw/AtcsLkuNpj+cDNMk86pnnzKmQ/QNSLMs7SXuyfvz2uWYwR+en4S+gZszAds2VqrWkaFyvjQsDhFIlWgjvFoA5ve0Db72MtobrehzsRCYWVI25HVHD8X/GaeEQXmg64YAZC1nHNO0bShBU=
  - secure: PKKGJGeVKbAZ0y4eP/o5QIwN0DqW4BHHP7OyoMt0RTSh6Lf+0ddvadC9kPn/3D/tI9hmOD86G1QAYFqUvM9pYqsIjMP85qaBNFQ3yDBAzWndOQvPkLYlbi1L1TQ6y7wm2tyyqOM0ndjcvTOF1MC9zPPcqqHwMP4EUVcWvHS7DTw=
  - secure: GuPpSmOT1Cza6ajeGs7QcQ9qef15+PmPWBM5XSXbz839qhQKOm3YZOhhGbvoYfTMkux5RPAzL5LartPUgiXDM0xYjnQoFfqZwBdP8ptYm2ypgmudMtYiKwmpBs5Yq+tAh69lw2WZSt7oJ0tCVLmWwhowk5ptU/tQm/XcP/Qv1Qk=
  - secure: P8BOLb9TZnTHVCzGNjPypHXokWxXBTMyR1x64bR9JXNN5//QRABDLm9GUzuN3viXX447o6XagmyGMOJFYB03LQlHG1vY5Eds+AOcVpVm3iAo9lAkBk4DUQY70rp6keInAoM+CdlTgIbeFLPn4vfng8vS5OnvXT3aWzbXhoHGPBw=
  - secure: b+n3sZU27cUxV2L0tCl9r4DCRkG0Ut1n25PVd7Lp9SPl7v1Wzp3xwO8BvYVXlVfsWS/UTzm0zDbnjWKEPWqLkGOlG7rTXxJITEMYBpNm4136/Zh+LuI4w2Dh/dWU12GEXobHx+nYk4Vaf2A0TCuszZOla3n3yoQn5FabjsBgJKM=
  - secure: DeDeuv5APfGst/2JkiE/Nws5ZcEA394YghXy27mx8yAXLJqqoTlKQHumQDxAo31wTpSCtDvXlQ9J9nSY9B9xaQD5p/pMcCa+CmAQW/b0RbG2pPTy86PEKnkJTNJIv86jFOg5JFeEqz39wEbE57v3kwDNeVIdUSd6IhLzAzIZpr4=
  - secure: Crue2+pUFhoQxao3E6WZtSoSaWUcyEb+o72AQ4eY1he+//TljNQ2n8S+L0ez3h3RfsIAW2wug1G0V4dMRExjM58DVQYjeGFJbdy8CAy7WebhJBodZzQ+JHt3fU+Jj/PRwsDwhPvDWU7IS3R86DTcQOVBk9FRZ23RbI3AsEt8Mmc=
  - secure: AYdd5OD4iHWiYA/JxwDHmfPESG7jbD/SVMlBa1xz9TMIvAtW3WMToXjL5JBsw6KyRhod2ec7Jx0mZ5EZ1YphAOgjmsCJDDN92hda61dKmkdI+QIfW2law4rWLelJ5cQfP4Pzy9rP11PKry1JspVH0rERd+wlKtp4EP8TO/7N4zs=
  - secure: J7UzKysJAZSNuDJeDIXfMqMFkfngSQPsYLaJJAlWlyxR6+rdX0JaVQy8OOSlQdygaVQHwRNKbv2ymq9RqkWCM2tAfvVay1DwwlgMtgnvm+4AoD5to4+fhXb7Im6eMY1jQ2k6BuABGLTjYv103OUEYwGHbrvzDVdf6krMLgJgcBQ=
  - secure: fj5TgAs8B7yp4Q81stI76Cef4bZ5LJlbmn39M7Wwkoowb39HBl6GkJtT9npvYZo5CgQg4Vkhy3HanqZJPkJrOXq3Di3wSNNqZOxUKLwPY/sl/WH02HcQDTIZ5yt10WkWuVXZY9aRmC0VBM5qNgNV4Ue1017HYiX7r5cl6kQTqIU=
