language: ruby
rvm:
- 2.1.0
branches:
  only:
  - master
before_script:
- git config --global user.name "yasuoza(via Travis CI)"
- git config --global user.email "yasuharu.ozaki+travisci@gmail.com"
- git remote set-url origin $REPO.git
- for (( i=0; i<=$RSA_LENGTH; i++ )); do eval "echo -n \$id_rsa_$i >> ~/.ssh/travisci_rsa_64"; done
- base64 --decode --ignore-garbage ~/.ssh/travis_rsa_64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- rake setup_github_pages[$REPO]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - REPO="git@github.com:yasuoza/blog.yasuoza.com.git"
  - secure: TKIU6edbEQt7qVNMwLzvfVv4J04rFbGfV/YazSG/QcBWxwrneXapZMZUH0fU+swwWl/xEYlZYG7PRWGFLDXIe+68faSUQXLRG5SPE3xsD6pB+dLpfc/GUmQnXxmhYt+ShI7/+FpK32fNQgh4VnLf3qJYwDKP/INHch7PSVFwqRk=
  - secure: OIl6MidyWp4D5hQ0T70g64iXxqBsxuF0PBgSoM0zmzvlY4rxBzALfLyMaEfiGWzXe8WT/OmtKY+TjY9d77mwC+FIguLYIrneFeBrt1+di+gJFPf+xwA2LMZZeC+bHVYH4obRQaAlOkmJSHHITDdf1eDxrX2cozZHudxwp+sNfvA=
  - secure: BUsdsohI4u3wbDxuAr1/S+7DxWJlMkZHkBlx0jLkLMOEY/B0w0NnCo+Kr1TOHe2IK5Q2nVA2Q8V6XHcX9WKYYQcCnugikWb+FkH25//GH9bs4rx/qTUhuYBwT+O5VQQC+EWzHVOYgPL9BCR2FZwP55uDsz1XNwp4xij51PoyIbI=
  - secure: GpNkeOGd5BvNPXfPcj+hJvw6LHe+Xdtw9NILS5yye/Q9zUwsn22XeIkvXzqZozmXK1+2xVdUiacUpK/53C3Kjv79TKI6CK2VFAZwnF6bibClz+NJ1lc9RXYRfh8UYz+wEPS+qt7tu8NxJjvBXRyjct5Co8eemQ88jAN/XOJZ6T8=
  - secure: MWTalcXKHfP5hApn/+ZR4CyVVd+zq1lR2EdwMT/hc0PwD2ERNgHyWGCXTZbHd6AVVYrK3CJFBSn0kNN0Bc9pube0Eq/MdAQmVbb04yrF3T36Ij2+BVJUveBpJpjuIt30BG48/DxMvtm7YFrwD5eCwI5vJD23RDHkDkBUQ06TeoY=
  - secure: aYunWwIxxeURBFTCqDcPpr4KFv2SFlbxVpfCegYBgZutQ6Qs/IzJ7nhSvN7r5hNPJPgdxeJX0B5Hdg8fgwPP8xjsceOt0T3RoBanzkRG+PBJfLO9TYRQ7xzsNnSg+SdTn3LyQCgDCGuYoWZ9g1tUULD2SeTiX0j7/ZQ10GYvyfw=
  - secure: NlCzywiGy4csl/JgqC75u+FeOiQL0ss5ycw52ktxFy4OW1PuJRy+A2gMoETKlPvzvUDkM3roJVCRoloE8ighCMQfmY+OyGiPZvNfeHCRsqlBUb3GDxdA6qRnaK/f7p20+laAigwN1HDdXA9IiMF5K5jcH3jHDzL0brTfaxNiB0I=
  - secure: BT9NzgJKXb59qb6bvo8c9RQE4rZHKBI8aFB3MxL4FJxA1f+PsgYAng9B+8KrzmRD5JgcaMOd2sghUF9vKgtSwH8FtiF2KzkX1xXPlgVE+UJyvo7Gvzxc0FLiAXU8Sziq+t+S/hS7O6tdEpsQKXRPbHN7CuQ8BK+fuSNvonlzM9o=
  - secure: CxgDJDEic70pZ5NwLJ2HwHTMXXw6GjVcpibx7WXI4hKhcjBfzOVeLcyPb/b/y4CY6TFNTVJJ7oqkDhVGsP+RTd05Bl/rgDQkkNGIBWiSsCSYW7MXg3g6FYHiYOQTyzLk9zbweNNG3ScXmApwZszhM14Q8V4b9SfZAYf1FG2+G3I=
  - secure: H+oBXo42zy+fLizNmXt/UNkj7Fs87ugmM+kdaXUYE41ODOQED5/764dkKR/HfyGAx0ZVOt+MSxlb1NgqSoti6xx8LgvgJsT6YwDlUHybSLCYYpo9ijaAxRKRaKT03O2WJiRQ6DjLKfJ3VLBsg57puJ7v008UhVXEVND8gDFFqq0=
  - secure: BMRsxbLPuJGlm+gTRGoaUEsSwem7ql0OeQOfJtodBjgJ8qi5csBnM7mF+WXgHgUhZMEsy8pwrK3RVXwgj526J4yIUqL/6TbtzsZMqoRUdkKNU5ZxIe1v9oXKpz1ULHcFrEXv5+88Ic9stzIbSlK517g1iqn7EWB1cFCPFWPVbUY=
  - secure: gayCK+c3xtEAz2+97/OwbM1dlo6lZ/u+qwzVvR9P/IRQZozSfCIr13eb8/s5wxb3KDKZ45mdGJubUUXfXqCIAlRYDVOmRkKx3wjc6yqW+7UIkUzYCEnt2UHI4UAP7rT/2E0H6EyAdOdSD2XKU/niuzFirzsB9D73mozihxALww0=
  - secure: Yu2nOg5EUNWFGKwibRXoXLHqOfpuyefekjkeDJ0Xgt4Krov+v29oXOnS0PM9pQ9R0AjO9EPXvY0RzfuWTv3Z2UB0l96yBZY1UDMV+34dIY8S47uI4mhvvKKw1YhVvJpwXXZNkMI2lmCwbP0pbRvGgJEbFykqziv9oClAUwNetos=
  - secure: R6q1z1ZDxLltHHTqUjKZlZfDUT5AJe5lMRUrXqNyH56bW3HgLu4RHeQVxa0myhTzvoX4Ftp7eqf5YYPxA/usycIJrSVJO/fi75xpOmywtSEJbna+ZEbMhEPbU7mtpi9zC/xMiVq+EkF3HXfa0DTwDnTtoWiBNk79QW9uCwQ97fY=
  - secure: dDL4et48ys9mr2vIS9uytPbkYMx14w66Do0HQuWTVn/0SJJeAGByr76dcuC6Y5lt9ravRDXu7BLFyiGBPMfY32VmWzSbymd3wewkKs+wmJxk+t0UXMv38mMl5xIi6grX1WshmFHqIbs278ZBnTCiHjf3KKnnxbLIlomAj+NJbkw=
  - secure: afsFbHXj4KztQT/3AShHLKlAfwG78NalkuaPpSAT+wbfnIvtUI5dFUiOvWBYHMqhMDMw0ub6TBMhvokhw1lQ9zilU0cSsrHnLWAAQPWdz1M4cL2abR/czzC5LvuSD16voWT6ZE2snorB1NAD7cqkiQQM1ZwH1G0x0vG7++aKaLo=
  - secure: N0b0smJjm9nYGX2YQdXSynLVVSM++f/2sWc2iFAqBjGZbyjYRbQK5GAZEAh3dufNXBuIrObeBD1m9FWrqiSoue5KMCDa+TUa6b+rNUCTySGp6kl72K5qncIIUKfjBaeVAy2VEJLs6AB6bFXK3Z8Yu055ebcqr2gBnY43dQc9g+w=
  - secure: HXbzYqr40p3Qu0gDm0P9JLX7B2uCbtdoQFxfV7b0kigWr0JB9Z6fdBPl7nms+ab+8UT5UnuTuV92vAd3ZdxFnIOHeRdYLubbFuGLo0N7m9wXgOMpKJg3vs7eXuDA7z+m4vS7dWzUhi4VVnFLKf5u4gl08p1yFffzg6lk/hlBasA=
  - secure: dQSI79SwMw2qny8tkGmkhVqmzKG8VAiPoi7Goo3wa5X0kIZPvTh4bZYdmGjsnn4VDM5naxBN/nbuW+hgUbR192h4DXfEd6nvvramhM5m69B0TQmPiLNeo3hrblPRpAAh4Dg1EYtaSzTeeQ7QwyLjIjRcSXpRaRg7msvhhcguGOY=
  - secure: RfMMzwZX+nBeAhjuz+iefuC3kJqNeFNLjbtz1MQxo/farIBMlpfeY9VvRL4SRAS+f8pC2Z7azTDru3U6slk7IVXMmeetskzr3dqetzQPHiKG9/dsyPriUSWZL0hbnzOyUY2tNKZXNiAREGmfXBvLns77IqHDlgJ//WYDKbTPAJQ=
  - secure: TTlGPynZ6jVjSr3jTA/8V38zB1QtoLAqGkTP3cFkF1OcGLH4GE3hE5VaAzXo2RH+BpW/4D8sV2dsJuG0D0A9NtlRV2s/B27lgjNwxPcK1huZym9KSDWqCZwn84s1Po3SOalC5ozh/8V5+gxN+jHBaXXnwhXCm/fMV0bfsnAnxIs=
  - secure: YrHizVhDxrgDXrMR/XCE4NiDCBFGgsCa1MQoOMj60PZEIR+uGoXIiry03fsFs2tKgtqZvdO2Pwpm6EHSnzAe1cgYpUG53v+2HbT1kZExWSxa9DjffuIfh0yKhCKV28cXlqybYZ8dM4W4P71A4FFD0kRdaMl2ALy6Tn8dMHp9HUQ=
  - secure: axRRY4qLm1PUS45YzpYreSRiWsO8ecuCTglvcv+0Sh8lQOPNGiDG/qEUO/BU0wwxXRi6oNryTXjgZebr4KPt34G7fLkExnhm+GvFK2iUVz3XFv1LY2OMWSdq1OrqBEfOS301yqSLTHOXV0/tdF49bZwcJscWGemz9qv3D07A8Cc=
  - secure: VlhCslNQIJYrxsaT/kkCj9joX9tvboF5d8JNRzqemfPNYHqzzghJ9lR/7k9qqD8hdMLPZNlTTFYrgy12DXShoE3tbOVN2aqkQ8wEorfa2MlA1Vi+TrOEzSkO5RcU8kBljlqMxtTt8sBO/TkmNi6U0iB0trRUyVhASHMVOOKvA/Q=
